# Generated by Django 3.2.3 on 2021-05-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UldNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('PMC', 'PMC'), ('PLA', 'PLA'), ('AKE', 'AKE'), ('PYB', 'PYB')], max_length=3, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_owner', models.CharField(blank=True, choices=[('R7', 'R7')], max_length=3, null=True)),
                ('shipment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.shipment')),
            ],
        ),
    ]
