# Generated by Django 3.1.5 on 2021-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UldNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(blank=True, choices=[('PMC', 'PMC'), ('PLA', 'PLA'), ('AKE', 'AKE'), ('PYB', 'PYB')], max_length=3, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=5, null=True)),
                ('unit_owner', models.CharField(blank=True, choices=[('ABC', 'R7')], max_length=3, null=True)),
            ],
        ),
    ]
