# Generated by Django 3.1.5 on 2021-05-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20210525_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='str_hndl_temp',
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(default='XXX', max_length=3),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(default='XXX', max_length=3),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shc_code',
            field=models.CharField(default='XXX', max_length=10),
        ),
        migrations.CreateModel(
            name='SHC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shc_text', models.CharField(max_length=3)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.shipment')),
            ],
        ),
    ]
