# Generated by Django 3.1.5 on 2021-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20210525_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='shc_code',
        ),
        migrations.AddField(
            model_name='shipment',
            name='handling',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shc_code1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shc_code2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shc_code3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shc_code4',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shc_code5',
            field=models.CharField(default='', max_length=10),
        ),
    ]
