# Generated by Django 3.1.5 on 2021-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_auto_20210525_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shc_code1',
            field=models.CharField(choices=[('ICE', 'DRYICE'), ('MAG', 'MAGNETIC'), ('ELI', 'LITHIUM_ION'), ('COL', 'COOL'), ('ERT', 'ENVIROUNMENT'), ('CRT', 'COOLROOMTEMP'), ('NFR', 'NOFROZEN'), ('ACT', 'ACTING')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code2',
            field=models.CharField(choices=[('ICE', 'DRYICE'), ('MAG', 'MAGNETIC'), ('ELI', 'LITHIUM_ION'), ('COL', 'COOL'), ('ERT', 'ENVIROUNMENT'), ('CRT', 'COOLROOMTEMP'), ('NFR', 'NOFROZEN'), ('ACT', 'ACTING')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code3',
            field=models.CharField(choices=[('ICE', 'DRYICE'), ('MAG', 'MAGNETIC'), ('ELI', 'LITHIUM_ION'), ('COL', 'COOL'), ('ERT', 'ENVIROUNMENT'), ('CRT', 'COOLROOMTEMP'), ('NFR', 'NOFROZEN'), ('ACT', 'ACTING')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code4',
            field=models.CharField(choices=[('ICE', 'DRYICE'), ('MAG', 'MAGNETIC'), ('ELI', 'LITHIUM_ION'), ('COL', 'COOL'), ('ERT', 'ENVIROUNMENT'), ('CRT', 'COOLROOMTEMP'), ('NFR', 'NOFROZEN'), ('ACT', 'ACTING')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code5',
            field=models.CharField(choices=[('ICE', 'DRYICE'), ('MAG', 'MAGNETIC'), ('ELI', 'LITHIUM_ION'), ('COL', 'COOL'), ('ERT', 'ENVIROUNMENT'), ('CRT', 'COOLROOMTEMP'), ('NFR', 'NOFROZEN'), ('ACT', 'ACTING')], default='', max_length=3),
        ),
    ]
