# Generated by Django 3.1.5 on 2021-05-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20210525_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shc_code1',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('MAG', 'MAG'), ('ELI', 'ELI'), ('COL', 'COL'), ('ERT', 'ERT'), ('CRT', 'CRT'), ('NFR', 'NFR'), ('ACT', 'ACT')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code2',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('MAG', 'MAG'), ('ELI', 'ELI'), ('COL', 'COL'), ('ERT', 'ERT'), ('CRT', 'CRT'), ('NFR', 'NFR'), ('ACT', 'ACT')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code3',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('MAG', 'MAG'), ('ELI', 'ELI'), ('COL', 'COL'), ('ERT', 'ERT'), ('CRT', 'CRT'), ('NFR', 'NFR'), ('ACT', 'ACT')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code4',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('MAG', 'MAG'), ('ELI', 'ELI'), ('COL', 'COL'), ('ERT', 'ERT'), ('CRT', 'CRT'), ('NFR', 'NFR'), ('ACT', 'ACT')], default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shc_code5',
            field=models.CharField(blank=True, choices=[('ICE', 'ICE'), ('MAG', 'MAG'), ('ELI', 'ELI'), ('COL', 'COL'), ('ERT', 'ERT'), ('CRT', 'CRT'), ('NFR', 'NFR'), ('ACT', 'ACT')], default='', max_length=3, null=True),
        ),
    ]
