# Generated by Django 3.1.5 on 2021-05-25 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
        ('hub', '0008_auto_20210525_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='inbound_flight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
    ]
