# Generated by Django 3.1.5 on 2021-05-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uld', '0001_initial'),
        ('hub', '0010_auto_20210526_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='uld',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='uld.uldnumber'),
        ),
        migrations.DeleteModel(
            name='SHC',
        ),
        migrations.DeleteModel(
            name='UldNumber',
        ),
    ]
