# Generated by Django 3.1.5 on 2021-05-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20210526_1748'),
        ('hub', '0011_auto_20210526_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='outbound_flight',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.depflight'),
        ),
    ]
