# Generated by Django 3.1.5 on 2021-05-27 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uld', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trr_date', models.DateTimeField(blank=True, default='')),
                ('title', models.CharField(blank=True, max_length=55, null=True)),
                ('state_status', models.CharField(choices=[('NW', 'NEW'), ('OTF', 'OKTOFWD'), ('RCD', 'REJECTED'), ('CCD', 'CANCELED')], default='NEW', max_length=36)),
                ('is_completed', models.BooleanField(default=False)),
                ('standby', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trr_arr_flight', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.arrflight')),
                ('trr_dep_flight', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.depflight')),
                ('trr_shipment', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.shipment')),
                ('units', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='uld.uldnumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
