# Generated by Django 3.1.5 on 2021-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
